

title: Alexia Roux-Sibilon
#email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



description: > # description of the site (multiple lines allowed)
  <p>
  Bonjour! <br>
  description!
  <br> ????
  </p>
  
  <p>
  Some links -- <a href='https://scholar.google.com/citations?user=bniRun0AAAAJ&hl=fr&oi=ao'>google scholar</a>  <a href='https://github.com/AlexiaRoux-Sibilon'>github</a>   <a href='https://twitter.com/a_rouxsibilon'>twitter</a>  <a href='https://www.researchgate.net/profile/Alexia-Roux-Sibilon'>researchgate</a>  <a href='https://publons.com/researcher/3569257/alexia-roux-sibilon/'>publons</a> 
  <br> Feel free to contact me at a.roux-sibilon@uclouvain.be 
  </p>  


permalink: /:slug.html


favicon: "images/bird.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "←" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
